[workspace]
members = [
    "crates/gbx-alg",
    "crates/gbx-field",
    "crates/gbx-poly",
    "tests/engine",
    "tools/graph",
    "bin/graph_experiments"
    , "crates/gbx-grobner", "bin/baseline_experiments"]

exclude = ["bin"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-user/your-repo"
version = "0.1.0"

[workspace.dependencies]
gbx-alg = { path = "crates/gbx-alg" }
gbx-field = { path = "crates/gbx-field" }
gbx-poly = { path = "crates/gbx-poly" }

thiserror = "2"
criterion = "0.8.2"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"
anonymous_parameters = "warn"
missing_debug_implementations = "warn"
missing_copy_implementations = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
warnings = "warn"
variant_size_differences = "warn"


[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
cargo = "warn"
nursery = "warn"
restriction = { level = "allow", priority = -1 }

unwrap_used = "warn"
expect_used = "warn"
todo = "warn"
unimplemented = "warn"
missing_panics_doc = "warn"
missing_errors_doc = "warn"
explicit_iter_loop = "warn"
needless_collect = "warn"
enum_glob_use = "warn"

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
debug-assertions = true
lto = "off"


[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
debug = true
strip = "none"


[profile.bench]
opt-level = 3
lto = "thin"
codegen-units = 1
debug = true

[profile.test]
opt-level = 1
debug = true
overflow-checks = true
debug-assertions = true
lto = "off"
