[package]
name = "test-engine"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
instrumentation = [
    "gbx-grobner/instrumentation",
]
[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.2"
anyhow = "1.0.101"
thiserror = "2.0.18"
clap = { version = "4.5.59", features = ["derive"] }
gbx-poly = { path = "../../crates/gbx-poly" }
gbx-field = { path = "../../crates/gbx-field" } # if needed
gbx-grobner = { path = "../../crates/gbx-grobner" }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[lints]
workspace = true
