use crate::utils::test_file_config::TestCase;

#[allow(missing_docs, dead_code)]
#[derive(Debug, Clone)]
pub struct SingularProgram {
    pub script: String,
    pub ring_decl: String,
    pub ideal_decl: String,
}

#[derive(Debug, thiserror::Error)]
pub enum MapError {
    #[error("case `{case}` : {msg}")]
    TestCase { case: String, msg: String },
}

pub fn map_test_case_to_singular(case: &TestCase) -> Result<SingularProgram, MapError> {
    let ctx = TestContext::new(case);

    let char_part = map_characteristic(&ctx)?;
    let vars_csv = format_vars(&ctx)?;
    let order = validate_order(&ctx)?;
    validate_generators(&ctx)?;

    let ring_decl = build_ring_decl(&char_part, &vars_csv, &order);
    let ideal_decl = build_ideal_decl(&ctx.case.generators);

    let script = render_script(&ctx, &ring_decl, &ideal_decl);

    Ok(SingularProgram { script, ring_decl, ideal_decl })
}

struct TestContext<'a> {
    test_case_name: &'a str,
    case: &'a TestCase,
}

impl<'a> TestContext<'a> {
    fn new(case: &'a TestCase) -> Self {
        Self { test_case_name: &case.name, case }
    }
    fn err(&self, msg: impl Into<String>) -> MapError {
        MapError::TestCase { case: self.test_case_name.to_string(), msg: msg.into() }
    }
}

fn map_characteristic(ctx: &TestContext<'_>) -> Result<String, MapError> {
    match ctx.case.field.as_str() {
        "Fp" => {
            if ctx.case.p <= 1 {
                return Err(ctx.err(format!("field=Fp requires prime p>1, got {}", ctx.case.p)));
            }
            Ok(ctx.case.p.to_string())
        }
        other => Err(ctx.err(format!("unsupported field '{other}' (expected 'Fp')"))),
    }
}

fn format_vars(ctx: &TestContext<'_>) -> Result<String, MapError> {
    validate_vars(ctx)?;
    Ok(ctx.case.vars.join(","))
}

fn validate_vars(ctx: &TestContext<'_>) -> Result<(), MapError> {
    if ctx.case.vars.is_empty() {
        return Err(ctx.err("vars must be non-empty"));
    }

    for v in &ctx.case.vars {
        if !is_safe_ident(v) {
            return Err(ctx.err(format!(
                "invalid variable name '{v}' (allowed: [A-Za-z_][A-Za-z0-9_]*)"
            )));
        }
    }
    let mut sorted = ctx.case.vars.clone();
    sorted.sort();
    sorted.dedup();
    if sorted.len() != ctx.case.vars.len() {
        return Err(ctx.err("vars contain duplicates"));
    }

    Ok(())
}

fn validate_order(ctx: &TestContext<'_>) -> Result<String, MapError> {
    let order = ctx.case.order.trim();
    let ok = matches!(order, "dp" | "lp" | "Dp" | "rp" | "wp" | "Wp" | "ds" | "ls");

    if !ok {
        return Err(ctx.err(format!(
            "unsupported or unsafe order '{order}' (allowed: dp, lp, Dp, rp, wp, Wp, ds, ls)"
        )));
    }
    Ok(order.to_string())
}

fn validate_generators(ctx: &TestContext<'_>) -> Result<(), MapError> {
    if ctx.case.generators.is_empty() {
        return Err(ctx.err("generators must be non-empty"));
    }
    Ok(())
}
fn build_ring_decl(char_part: &str, vars_csv: &str, order: &str) -> String {
    format!("ring R = {},({}),{};", char_part, vars_csv, order)
}

fn build_ideal_decl(generators: &[String]) -> String {
    format!("ideal I = {};", generators.join(", "))
}

fn render_script(ctx: &TestContext<'_>, ring_decl: &str, ideal_decl: &str) -> String {
    format!(
        "// AUTO-GENERATED by gbx-test-engine\n\
         // case: {case_name}\n\
         \n\
         {ring}\n\
         {ideal}\n\
         \n\
         ideal G = groebner(I);\n\
         int n = size(G);\n\
         for (int i = 1; i <= n; i = i + 1) {{\n\
           print(\"GB:\" + string(G[i]));\n\
         }}\n\
         quit;\n",
        case_name = ctx.test_case_name,
        ring = ring_decl,
        ideal = ideal_decl,
    )
}

fn is_safe_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}
