[package]
name = "gbx-grobner"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
instrumentation = ["dep:tracing"]


[dependencies]
gbx-alg = { path = "../gbx-alg", default-features = false }
gbx-storage = { path = "../gbx-storage", default-features = false }
gbx-field = { path = "../gbx-field", default-features = false }
gbx-poly = { path = "../gbx-poly", default-features = false }
thiserror = "2.0.18"
tracing = { version = "0.1.44", optional = true }

[lints]
workspace = true
