[package]
name = "gbx-poly"
version = "0.1.0"
description = "Polynomial data structures, monomial orders, and reduction algorithms for GBX."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
keywords = ["polynomial", "grobner", "algebra", "math"]
categories = ["mathematics", "science"]


[features]
default = ["std"]
std = []

[dependencies]
gbx-alg = { path = "../gbx-alg", default-features = false }
gbx-field = { path = "../gbx-field", default-features = false }
thiserror = "2.0.18"
criterion = "0.8.1"
tracing = "0.1.44"

[lints]
workspace = true

[[bench]]
name = "reduction"
harness = false
