[package]
name = "gbx-poly"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true


[features]
default = ["std"]
std = []

[dependencies]
gbx-alg = { path = "../gbx-alg", default-features = false }
gbx-storage = { path = "../gbx-storage", default-features = false }
gbx-field = { path = "../gbx-field", default-features = false }
thiserror = "2.0.18"
criterion = "0.8.1"

[lints]
workspace = true

[[bench]]
name = "reduction"
harness = false
