[package]
name = "gbx-field"
version = "0.1.0"
description = "Runtime prime fields for the GBX ecosystem."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

keywords = ["algebra", "field", "finite-field", "math"]
categories = ["mathematics", "science", "no-std"]

[features]
default = ["std"]

std = ["gbx-alg/std"]

laws = ["gbx-alg/laws"]

[dependencies]
gbx-alg = { path = "../gbx-alg", default-features = false }
thiserror = "2.0.18"

[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }

[lints]
workspace = true

[[bench]]
name = "bench"
harness = false
