name: CI
on: [push, pull_request]
jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@master
              with: { toolchain: 1.85.0, components: clippy,rustfmt }
            - run: cargo fmt --all -- --check
            - run: cargo clippy --workspace --all-targets -- -D warnings
            - run: cargo test --workspace --all-features
    benches:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@master
              with: { toolchain: 1.85.0 }
            - run: cargo bench --workspace || true
